<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists

def transpose(M):
    X = [ [row[i] for row in M ] for i in range(len(M[0])) ]
    return X
                
def multiplyRow(row1,row2):
    ssum=0
    for i in range(len(row1)):
        ssum += row1[i]*row2[i]
    return ssum

def matrix_mul(A, B):
    
    # Checking Compatablity of the Matrix for Multiplication 
    if len(A[0]) != len(B): # A (n x m) B (c x d) then m == c
        return None # Not Possible to Multiply
    
    
    B_t = transpose(B) # Taking Transpose to Make coloumn as rows
    AB = list()
    for rowA in A:
        rowAB = list()
        for rowB in B_t:
            rowAB.append(multiplyRow(rowA,rowB))
        AB.append(rowAB)
    
    return AB

"""Example 1"""
A   = [[1, 3, 4],
       [2, 5, 7],
       [5, 9, 6]]
B   = [[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]
print( "Example 1 : " , matrix_mul(A, B))

"""Example 2"""
A   = [[1 , 2] ,[3 , 4]]
B   = [[1, 2 ,3 ,4 ,5] ,[5,6 ,7 ,8 ,9 ]]
print( "Example 2 : " , matrix_mul(A, B))

"""Example 3"""
A   = [[1, 2],
        [3, 4]]
B   = [[1, 4] , [5, 6] , [7, 8] ,[9, 6]]
print( "Example 3 : " , matrix_mul(A, B))


Example 1 :  [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
Example 2 :  [[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]
Example 3 :  None


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [74]:
from random import uniform
import numpy as np
import pandas as pd
np.set_printoptions(precision=3)
A = np.array([0 ,5 ,27 ,6 ,13 ,28 ,100 ,45 ,10 ,79])
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure

def printCDF(A):
    total = np.sum(A)
    cdf = list()
    csum = 0
    for k in A:
        cdf.append(csum + k)
        csum+=k
    print(np.array(cdf)/total)
        


count_dict = dict()
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    a = np.random.uniform(0,1)
    
    
    #print("Befofe Sort : ", A)
    A.sort()
    #print("After Sort : ", A)
    total = sum(A)
    cdf = list()
    csum = 0
    for i in A:
        cdf.append(i+csum)
        csum+=i
    
    ans = -1
    for i in range( len(A) ):
        if( cdf[i]/total >= a):# First Time a gets small then Probablity 
            found = True
            ans = A[i]
            break
    if(ans == -1):
        ans = A[-1]
    return ans

def sampling_based_on_magnitued():
    for i in range(1,10000):
        
        number = pick_a_number_from_list(A)
        
        if(count_dict.get(number) is None):
            count_dict[number]=1
        else:
            count_dict[number]+=1
            
        #print(number)

sampling_based_on_magnitued()



keys = list(count_dict.keys())

for value in A:
    if( value not in keys):
        keys.append(value)
        count_dict[value]=0
sorted_keys = sorted(keys)
values = [ count_dict[key] for key in sorted_keys]

result = pd.DataFrame({ "Values" : sorted_keys  ,
                        "Ground Truth Probablity" : np.array(sorted_keys)/(np.sum(sorted_keys)),
                       "Exprimental Probablity Values" :np.array(values)/sum(values)
                      })
result

Values  Ground Truth Probablity  Exprimental Probablity Values
0       0                 0.000000                       0.000000
1       5                 0.015974                       0.016402
2       6                 0.019169                       0.019702
3      10                 0.031949                       0.033503
4      13                 0.041534                       0.039004
5      27                 0.086262                       0.088609
6      28                 0.089457                       0.093609
7      45                 0.143770                       0.137314
8      79                 0.252396                       0.250025
9     100                 0.319489                       0.321832

This was the General trend That we were expecting because Greater the Values its chances of occurrence will increase the Exprimental results are close to Groud Truth but and gets closer to groud truth as we increase the no of sample we draw also it should be impossible to get exatcly same result as our uniform function in not truly random we even then we have to draw a large sample size

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [43]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    #
    newString = str()
    for c in String:
        if( c.isnumeric()):
            newString+='#'
        else:
            newString+=c
            
    return newString # modified string which is after replacing the # with digits
String = "#2a$#b%c%561#"
replace_digits(String)

'##a$#b%c%####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [7]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

def print_table(table):
    
    for k,v in table:
        print(k , " : ",v)
    

def display_dash_board(students, marks):
    
    n = len(marks)
    q1,q3 =  int((n+1)/4) ,int(3*(n+1)/4)
    if(n%2 == 0 ):
        q1 = int(n/4)
        q3 = int((3*n)/4)
    
    Student_Marks = list(zip(students,marks))
    
    Student_Marks.sort(key = lambda x:x[1])
    #print(Student_Marks)
    # write code for computing top top 5 students
    top_5_students = Student_Marks[-5:]# compute this
    
    # write code for computing top least 5 students
    least_5_students = Student_Marks[:5] # compute this
    
    # write code for computing top least 5 students
    students_within_25_and_75 = Student_Marks[q1:q3]# compute this
    
    return top_5_students, least_5_students, students_within_25_and_75


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(" Top 5 : \n")
print_table(top_5_students)
print("\n\n")
print(" Least 5 : \n")
print_table(least_5_students)
print("\n\n")
print(" Student within 25% to 75% : \n")
print_table(students_within_25_and_75)

 Top 5 : 

student7  :  47
student5  :  48
student2  :  78
student10  :  80
student8  :  98



 Least 5 : 

student3  :  12
student4  :  14
student9  :  22
student6  :  43
student1  :  45



 Student within 25% to 75% : 

student9  :  22
student6  :  43
student1  :  45
student7  :  47
student5  :  48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [84]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

def dotProduct(a,b):
    
    return sum([ai*bj for ai,bj in zip(a,b)])

def mod(a):
    temp = sum([ai**2 for ai in a])
    return math.sqrt(temp)

def cosineDist(a,b):
    dot_ab = dotProduct(a,b)
    mod_a = mod(a)
    mod_b = mod(b)
    val  = dot_ab/(mod_a * mod_b)
    return math.acos(val)


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    dist = list()
    for sp in S:
        dist.append((sp ,cosineDist(sp,P) ))
    sorted_point = sorted(dist,key = lambda x:x[1])
    #print(sorted_point)
    
    return sorted_point[:5]  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
pd.DataFrame({ "Points"  : [point[0] for point in points] ,
              "Distance" : [point[1] for point in points] ,})

Points  Distance
0   (6, -7)  0.065125
1   (1, -1)  0.141897
2    (6, 0)  0.927295
3  (-5, -8)  1.202100
4  (-1, -1)  1.428899

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [94]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

def lineCoff(line):
    
    newline = ''
    for c in line:
        
        if c in ['x','y']:
            newline+=','
        else:
            newline+=c
    coff = [ float(i) for i in newline.split(',')]
    return coff        

def which_side(a,b,c,points):
    
    val = [a*p[0]+b*p[1]+c for p in points ]
    
    positive = all([ True if(v > 0) else False for v in val ])
    
    negative = all([ True if(v < 0) else False for v in val ])
    
    if(positive):
        return 1
    if(negative):
        return -1
    return 0


def i_am_the_one(red,blue,line):
    # your code
    xc,yc,c =lineCoff(line)
    label_red = which_side(xc,yc,c,red)
    label_blue = which_side(xc,yc,c,blue)
    ans = "NO"
    if( label_red * label_blue == -1):
        ans = "YES"
    
    return ans

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>


In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    print("Question : ", string)
    values = [ None if v == '_' else int(v)  for v in string.split(',')  ]
    
    empty = 0
    st ,end =-1,-1
    for idx,v in enumerate(values):
        if(v is None):
            empty+=1
        else:
            if(empty == 0):
                st= v
            else:
                if(st == -1):
                    st = v
                    put = st/(empty+1)
                    for i in range(idx-empty,idx+1):
                        values[i]= put
                    empty=0
                    st = put
                else:
                    end = v
                    put = (st+end)/(empty+2)
                    for i in range(idx-empty-1,idx+1):
                        values[i]= put
                    empty = 0 
                    st = put
    
    if(empty != 0):
        put = st/(empty+1)
        for i in range(idx-empty,idx+1):
            values[i]= put
        
    print("Answer : ", ",".join([ str(i) for i in values]))
    print()
    return values

S=  ["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]
for q in S:
    curve_smoothing(q)


Question :  _,_,_,24
Answer :  6.0,6.0,6.0,6.0

Question :  40,_,_,_,60
Answer :  20.0,20.0,20.0,20.0,20.0

Question :  80,_,_,_,_
Answer :  16.0,16.0,16.0,16.0,16.0

Question :  _,_,30,_,_,_,50,_,_
Answer :  10.0,10.0,12.0,12.0,12.0,12.0,4.0,4.0,4.0



<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns <br>
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
<br>
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [11]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure

def countFgivenS(A,F,S):
    
    sample_space = [ pair for pair in A  if pair[1]==S ]
    fav_outcome = [pair for pair in sample_space if pair[0] == F]
    print("P(F={}|S=={})={}/{}".format(F,S,len(fav_outcome),len(sample_space)) , end=", ")
    


def compute_conditional_probabilites(A):
    
    uniqueF = sorted(list(set([ pair[0]  for pair in A ])))
    uniqueS = sorted(list(set([ pair[1]  for pair in A ])))
    for f in uniqueF:
        for s in uniqueS:
            countFgivenS(A,f,s)
        print()
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

print("\n\n\n")
compute_conditional_probabilites(A)






P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3, 
P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3, 
P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3, 
P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3, 
P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3, 


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [49]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S1_word = set(S1.split())
    S2_word = set(S2.split())
    commmon_words = S1_word & S2_word
    a = len(S1_word & S2_word)
    print("Common Words : ", a ,"\n", S1_word & S2_word)
    b = len(S1_word -S2_word )
    print("S1 - S2 : ", b ,"\n", S1_word - S2_word)
    c = len(S2_word - S1_word)
    print("S2 -S1 : ", c ,"\n", S2_word - S1_word)
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)

Common Words :  7 
 {'contain', 'values', 'will', 'uniques', 'column', 'the', 'only'}
S1 - S2 :  3 
 {'first', '5', 'F'}
S2 -S1 :  3 
 {'second', 'S', '3'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [105]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    n = len(A)
    #print(n)
    csum = 0
    for y,ys in A:
        csum+= y*math.log(ys,10) + (1-y)*math.log(1-ys,10)
    return -csum/n
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
